### ISSUE TITLE
Pattern of validate Host

### ISSUE THREAD

**Issue by Kevinsillo** [ACP-CODE/astro-robots#1]
The URL Host "https://kevinillanas.dev" does not validate for me. I think the error is in the validated pattern, because I have been able to solve it temporarily with another pattern, but I am not a regex expert.:

The function I am referring to:
```javascript
function validateHost(host, logger) {
  const hostPattern = /^(?=.{1,253}$)(?:(?!-)[a-zA-Z0-9-]{1,63}(?<!-)\.)+[a-zA-Z]{2,63}$/;
  if (typeof host !== "string") {
    throwMsg("Host must be a string", "error", logger);
  }
  if (!hostPattern.test(host)) {
    throwMsg("Host is invalid", "error", logger);
  }
}
```

**Comment by mendicantbias343** [comment]
Yep... same problem. The host is throwing as invalid.

**Comment by JakiChen** [comment]
Heyyyyyyy,

@Kevinsillo ,
@mendicantbias343 

In the `robots.txt` file, the Host field does not need to contain prefixes such as `https://` or `http://`. You only need to specify the hostname. For example:

```yaml
User-agent: *
Disallow: /
Host: www.example.com
```
